{% set name = "ligo.em-bright" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ligo.em-bright-{{ version }}.tar.gz
  sha256: 0bdcc91abd8316e11966f5a5fc15fbccf2591fbe15f169228ba425e61497ac3b
  patches:
    # we don't need the whole lalsuite, just a few components
    - no-lalsuite.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - em_bright_categorize = ligo.em_bright.categorize:main
    - em_bright_categorize_all_eos = ligo.em_bright.categorize:main_all
    - em_bright_create_param_sweep_plot = ligo.em_bright.utils:param_sweep_plot
    - em_bright_dag_writer = ligo.em_bright.dag_writer:main
    - em_bright_extract = ligo.em_bright.utils:extract
    - em_bright_join = ligo.em_bright.utils:join
    - em_bright_train = ligo.em_bright.utils:train

requirements:
  host:
    - pip <21.3
    - poetry-core >=1.0.0
    - python >=3.8,<4.0
  run:
    - astropy >=5.1
    - h5py >=2.10.0
    - pandas >=1.0,<2.0
    - python >=3.8,<4.0
    - python-htcondor >=9.0.6
    - python-lal >=7.1.3
    - python-lalsimulation >=3.0.0
    - scikit-learn >=1.1.0,<2.0.0

test:
  requires:
    - matplotlib-base
    - pip
    - pytest
  commands:
    # check requirements
    - python -m pip check
    # run test suite
    - python -m pytest -ra --pyargs ligo.em_bright
    # check console scripts
    - em_bright_categorize --help
    - em_bright_categorize_all_eos --help
    - em_bright_create_param_sweep_plot --help
    - em_bright_dag_writer --help
    - em_bright_extract --help
    - em_bright_join --help
    - em_bright_train --help

about:
  home: https://pypi.org/project/ligo.em-bright/
  dev_url: https://git.ligo.org/deep.chatterjee/em-bright.git
  summary: Possibility and properties of Electromagnetically-bright sources of gravitational-wave events
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - deepchatterjeeligo
    - duncanmmacleod
