{% set name = "ligo.em-bright" %}
{% set version = "1.2.2" %}
{% set pypi_name = name|replace('.', '-') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name|replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1746b5a4f5d2a492f08faa2e215b291163a32300f429e243c725641a6c7e099c
  patches:
    # see https://git.ligo.org/duncanmmacleod/em-bright/-/commits/conda-patches/
    - 0001-pyproject.toml-update-requirements.patch

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - em_bright_categorize = ligo.em_bright.categorize:main
    - em_bright_categorize_all_eos = ligo.em_bright.categorize:main_all
    - em_bright_create_param_sweep_plot = ligo.em_bright.utils:param_sweep_plot
    - em_bright_dag_writer = ligo.em_bright.dag_writer:main
    - em_bright_extract = ligo.em_bright.utils:extract
    - em_bright_join = ligo.em_bright.utils:join
    - em_bright_train = ligo.em_bright.utils:train

requirements:
  host:
    - pip
    - poetry-core >=1.2.0
    - python >=3.10,<4.0
  run:
    - astropy-base >=6.0
    - h5py >=3.11.0
    - pandas >=2.2
    - python >=3.10,<4.0
    - python-htcondor >=9.0.6
    - python-lal >=7.1.3
    - python-lalsimulation >=3.0.0
    - scikit-learn ==1.5.1

test:
  requires:
    - matplotlib-base
    - pip
    - pytest
  commands:
    # check requirements
    - python -m pip check ligo.em-bright
    - python -m pip show ligo.em-bright
    # run test suite
    - python -m pytest -ra --pyargs ligo.em_bright
    # check console scripts
    - em_bright_categorize --help
    - em_bright_categorize_all_eos --help
    - em_bright_create_param_sweep_plot --help
    - em_bright_dag_writer --help
    - em_bright_extract --help
    - em_bright_join --help
    - em_bright_train --help

about:
  home: https://pypi.org/project/ligo.em-bright/
  dev_url: https://git.ligo.org/emfollow/em-properties/em-bright.git
  doc_url: https://emfollow.docs.ligo.org/em-properties/em-bright
  summary: Possibility and properties of Electromagnetically-bright sources of gravitational-wave events
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - atoivonen13
    - deepchatterjeeligo
    - duncanmmacleod
